export const imageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiTw9vKUkfzdUkGVByistee-qWWG21sxiU8IT8cSjfBw&s";

export const listData = [
  {
    availableForPickup: true,
    basePrice: {
      currencyIso: "NZD",
      formattedValue: "$5.45",
      priceType: "BUY",
      value: 5.45,
    },
    configurationInfos: [],
    customProductFlag: false,
    decimalQty: 1,
    deliveryOrder: true,
    entryNumber: 0,
    estimateProductStock: 0,
    product: {
      alternateProductCount: 0,
      appUomFormat: "7.2",
      availableForPickup: true,
      baseOptions: [],
      categories: [
        {
          code: "AB01DA",
          name: "Sg8 H1.2 Rad PG Kd Scantlings 75Mm-100Mm",
          url: "/timber-panels/structural-grade-timber-kiln-dried/sg-h12-radiata-kd/sg8-h12-rad-pg-kd-scantlings-75mm-100mm/c/AB01DA",
        },
      ],
      code: "1015262",
      configurable: true,
      display: "PURCHASABLE",
      expressOrder: false,
      hasAlternateProducts: false,
      hasNoQuantity: 0,
      hasRelatedProducts: true,
      ProductDescription: "L’OCCITANE Immortelle Precious Cream",
      pmExclusive: false,
      price: {
        currencyIso: "NZD",
        formattedValue: "$5.45",
        priceType: "BUY",
        value: 5.45,
      },
      purchasable: true,
      relatedProductCount: 5,
      retailPrice: {
        currencyIso: "NZD",
        formattedValue: "$8.86",
        priceType: "BUY",
        value: 8.86,
      },
      retailPriceGstInclusive: {
        currencyIso: "NZD",
        formattedValue: "$10.19",
        priceType: "BUY",
        value: 10.19,
      },
      sellOrderMultiple: 6,
      specialProdWithAlphaSkuFlag: false,
      specialProduct: false,
      stock: {
        isValueRounded: false,
        pmStockQuantity: "12678",
        statusCode: "1",
        stockLevelStatus: "inStock",
      },
      timberProductFlag: true,
      unitCode: "LM",
      uomFormat: "7.2",
      url: "/timber-panels/structural-grade-timber-kiln-dried/sg-h12-radiata-kd/sg8-h12-rad-pg-kd-scantlings-75mm-100mm/100-x-50-90x45-rad-sg8-h12-planer-gauged-kd-60m/p/1015262",
    },
    quantity: 1,
    retailPrice: {
      currencyIso: "NZD",
      formattedValue: "$0.00",
      priceType: "BUY",
      value: 0,
    },
    selectedConfiguration: [
      {
        price: "32.7",
        quantity: "1",
        size: "6.0",
      },
    ],
    totalPrice: {
      currencyIso: "NZD",
      formattedValue: "$32.70",
      priceType: "BUY",
      value: 32.7,
    },
    totalSize: "6.00",
    unit: "LM",
    updateable: true,
  },
  {
    availableForPickup: true,
    basePrice: {
      currencyIso: "NZD",
      formattedValue: "$5.45",
      priceType: "BUY",
      value: 5.45,
    },
    configurationInfos: [],
    customProductFlag: false,
    decimalQty: 1,
    deliveryOrder: true,
    entryNumber: 0,
    estimateProductStock: 0,
    product: {
      alternateProductCount: 0,
      appUomFormat: "7.2",
      availableForPickup: true,
      baseOptions: [],
      categories: [
        {
          code: "AB01DA",
          name: "Sg8 H1.2 Rad PG Kd Scantlings 75Mm-100Mm",
          url: "/timber-panels/structural-grade-timber-kiln-dried/sg-h12-radiata-kd/sg8-h12-rad-pg-kd-scantlings-75mm-100mm/c/AB01DA",
        },
      ],
      code: "1015262",
      configurable: true,
      display: "PURCHASABLE",
      expressOrder: false,
      hasAlternateProducts: false,
      hasNoQuantity: 0,
      hasRelatedProducts: true,
      ProductDescription: "Kehl’s Creamy Eye Treatment with Avocado",
      pmExclusive: false,
      price: {
        currencyIso: "NZD",
        formattedValue: "$5.45",
        priceType: "BUY",
        value: 5.45,
      },
      purchasable: true,
      relatedProductCount: 5,
      retailPrice: {
        currencyIso: "NZD",
        formattedValue: "$8.86",
        priceType: "BUY",
        value: 8.86,
      },
      retailPriceGstInclusive: {
        currencyIso: "NZD",
        formattedValue: "$10.19",
        priceType: "BUY",
        value: 10.19,
      },
      sellOrderMultiple: 6,
      specialProdWithAlphaSkuFlag: false,
      specialProduct: false,
      stock: {
        isValueRounded: false,
        pmStockQuantity: "12678",
        statusCode: "1",
        stockLevelStatus: "inStock",
      },
      timberProductFlag: true,
      unitCode: "LM",
      uomFormat: "7.2",
      url: "/timber-panels/structural-grade-timber-kiln-dried/sg-h12-radiata-kd/sg8-h12-rad-pg-kd-scantlings-75mm-100mm/100-x-50-90x45-rad-sg8-h12-planer-gauged-kd-60m/p/1015262",
    },
    quantity: 1,
    retailPrice: {
      currencyIso: "NZD",
      formattedValue: "$0.00",
      priceType: "BUY",
      value: 0,
    },
    selectedConfiguration: [
      {
        price: "32.7",
        quantity: "1",
        size: "6.0",
      },
    ],
    totalPrice: {
      currencyIso: "NZD",
      formattedValue: "$32.70",
      priceType: "BUY",
      value: 32.7,
    },
    totalSize: "6.00",
    unit: "LM",
    updateable: true,
  },
  {
    availableForPickup: true,
    basePrice: {
      currencyIso: "NZD",
      formattedValue: "$5.45",
      priceType: "BUY",
      value: 5.45,
    },
    configurationInfos: [],
    customProductFlag: false,
    decimalQty: 1,
    deliveryOrder: true,
    entryNumber: 0,
    estimateProductStock: 0,
    product: {
      alternateProductCount: 0,
      appUomFormat: "7.2",
      availableForPickup: true,
      baseOptions: [],
      categories: [
        {
          code: "AB01DA",
          name: "Sg8 H1.2 Rad PG Kd Scantlings 75Mm-100Mm",
          url: "/timber-panels/structural-grade-timber-kiln-dried/sg-h12-radiata-kd/sg8-h12-rad-pg-kd-scantlings-75mm-100mm/c/AB01DA",
        },
      ],
      code: "1015262",
      configurable: true,
      display: "PURCHASABLE",
      expressOrder: false,
      hasAlternateProducts: false,
      hasNoQuantity: 0,
      hasRelatedProducts: true,
      ProductDescription: "Kehl’s Creamy Eye Treatment with Avocado",
      pmExclusive: false,
      price: {
        currencyIso: "NZD",
        formattedValue: "$5.45",
        priceType: "BUY",
        value: 5.45,
      },
      purchasable: true,
      relatedProductCount: 5,
      retailPrice: {
        currencyIso: "NZD",
        formattedValue: "$8.86",
        priceType: "BUY",
        value: 8.86,
      },
      retailPriceGstInclusive: {
        currencyIso: "NZD",
        formattedValue: "$10.19",
        priceType: "BUY",
        value: 10.19,
      },
      sellOrderMultiple: 6,
      specialProdWithAlphaSkuFlag: false,
      specialProduct: false,
      stock: {
        isValueRounded: false,
        pmStockQuantity: "12678",
        statusCode: "1",
        stockLevelStatus: "inStock",
      },
      timberProductFlag: true,
      unitCode: "LM",
      uomFormat: "7.2",
      url: "/timber-panels/structural-grade-timber-kiln-dried/sg-h12-radiata-kd/sg8-h12-rad-pg-kd-scantlings-75mm-100mm/100-x-50-90x45-rad-sg8-h12-planer-gauged-kd-60m/p/1015262",
    },
    quantity: 1,
    retailPrice: {
      currencyIso: "NZD",
      formattedValue: "$0.00",
      priceType: "BUY",
      value: 0,
    },
    selectedConfiguration: [
      {
        price: "32.7",
        quantity: "1",
        size: "6.0",
      },
    ],
    totalPrice: {
      currencyIso: "NZD",
      formattedValue: "$32.70",
      priceType: "BUY",
      value: 32.7,
    },
    totalSize: "6.00",
    unit: "LM",
    updateable: true,
  },
  {
    availableForPickup: true,
    basePrice: {
      currencyIso: "NZD",
      formattedValue: "$4.91",
      priceType: "BUY",
      value: 4.91,
    },
    configurationInfos: [],
    customProductFlag: false,
    decimalQty: 1,
    deliveryOrder: true,
    entryNumber: 1,
    estimateProductStock: 0,
    product: {
      alternateProductCount: 0,
      appUomFormat: "7.2",
      availableForPickup: true,
      baseOptions: [],
      categories: [],
      code: "1015021",
      configurable: false,
      description:
        "SG8 structural grade framing timber suitable for internal applications. Treated H1.2. Machine gauged to ensure dimensional accuracy and straightness. Ideal for frames & trusses.",
      display: "PURCHASABLE",
      expressOrder: false,
      hasAlternateProducts: false,
      hasNoQuantity: 0,
      hasRelatedProducts: false,
      images: [],
      manufacturerId: "2342163",
      ProductDescription: "Radiata SG8 Kiln Dried H1.2 Treated 75 x 50mm (70 x 45mm)",
      pmExclusive: false,
      price: {
        currencyIso: "NZD",
        formattedValue: "$4.91",
        priceType: "BUY",
        value: 4.91,
      },
      purchasable: true,
      relatedProductCount: 0,
      retailPrice: {
        currencyIso: "NZD",
        formattedValue: "$6.25",
        priceType: "BUY",
        value: 6.25,
      },
      retailPriceGstInclusive: {
        currencyIso: "NZD",
        formattedValue: "$7.19",
        priceType: "BUY",
        value: 7.19,
      },
      sellOrderMultiple: 0,
      specialProdWithAlphaSkuFlag: false,
      specialProduct: false,
      stock: {
        isValueRounded: false,
        pmStockQuantity: "0",
        statusCode: "3",
        stockLevelStatus: "outOfStock",
      },
      timberProductFlag: true,
      unitCode: "LM",
      uomFormat: "7.2",
      url: "/c/radiata-sg8-kiln-dried-h12-treated-75-x-50mm-70-x-45mm/p/1015021",
    },
    quantity: 1,
    retailPrice: {
      currencyIso: "NZD",
      formattedValue: "$0.00",
      priceType: "BUY",
      value: 0,
    },
    selectedConfiguration: [],
    totalPrice: {
      currencyIso: "NZD",
      formattedValue: "$4.91",
      priceType: "BUY",
      value: 4.91,
    },
    unit: "LM",
    updateable: true,
  },
];

export const catData = [
  { image: "https://thumbs.dreamstime.com/b/beautiful-rain-forest-ang-ka-nature-trail-doi-inthanon-national-park-thailand-36703721.jpg" },
  { image: "https://thumbs.dreamstime.com/b/beautiful-rain-forest-ang-ka-nature-trail-doi-inthanon-national-park-thailand-36703721.jpg" },
  { image: "https://thumbs.dreamstime.com/b/beautiful-rain-forest-ang-ka-nature-trail-doi-inthanon-national-park-thailand-36703721.jpg" },
  { image: "https://thumbs.dreamstime.com/b/beautiful-rain-forest-ang-ka-nature-trail-doi-inthanon-national-park-thailand-36703721.jpg" },
];

export const shoByCategorydata = {
  uid: "mobileLandingPage",
  uuid: "eyJpdGVtSWQiOiJtb2JpbGVMYW5kaW5nUGFnZSIsImNhdGFsb2dJZCI6InBsYWNlbWFrZXJzQ29udGVudENhdGFsb2ciLCJjYXRhbG9nVmVyc2lvbiI6Ik9ubGluZSJ9",
  title: "TradeApp Landing Page",
  template: "TradeAppLandingPageTemplate",
  typeCode: "ContentPage",
  name: "Mobile Landing Page",
  contentSlots: {
    contentSlot: [
      {
        slotId: "PMAppFooterSlot",
        slotUuid: "eyJpdGVtSWQiOiJQTUFwcEZvb3RlclNsb3QiLCJjYXRhbG9nSWQiOiJwbGFjZW1ha2Vyc0NvbnRlbnRDYXRhbG9nIiwiY2F0YWxvZ1ZlcnNpb24iOiJPbmxpbmUifQ==",
        position: "PMAppFooter",
        name: "Footer",
        slotShared: false,
        components: {
          component: [],
        },
      },
      {
        slotId: "PMMarketingTilesSlot",
        slotUuid: "eyJpdGVtSWQiOiJQTU1hcmtldGluZ1RpbGVzU2xvdCIsImNhdGFsb2dJZCI6InBsYWNlbWFrZXJzQ29udGVudENhdGFsb2ciLCJjYXRhbG9nVmVyc2lvbiI6Ik9ubGluZSJ9",
        position: "PMMarketingTiles",
        name: "Placemaker Marketing Tiles slot",
        slotShared: false,
        components: {
          component: [
            {
              uid: "cmsitem_00005000",
              uuid: "eyJpdGVtSWQiOiJjbXNpdGVtXzAwMDA1MDAwIiwiY2F0YWxvZ0lkIjoicGxhY2VtYWtlcnNDb250ZW50Q2F0YWxvZyIsImNhdGFsb2dWZXJzaW9uIjoiT25saW5lIn0=",
              typeCode: "PMMarketingTileComponent",
              modifiedtime: "2022-12-14T20:00:37.296+13:00",
              name: "Estimates tile 2022",
              container: "false",
              darkBackground: "true",
              ctaText: "Learn More",
              footerText: "Decking information and projects to help you sell the job.",
              backgroundImage: {
                container: "false",
                uid: "PMMobileCollectionBackGroundImage",
                name: "Decking Tile",
                synchronizationBlocked: "false",
                media: {
                  widescreen: {
                    code: "decking-inspo-app.jpg",
                    mime: "image/jpeg",
                    altText: "decking-inspo-app.jpg",
                    url: "/medias/sys_master/root/h22/h9c/9087433375774/decking-inspo-app/decking-inspo-app.jpg",
                  },
                },
                uuid: "eyJpdGVtSWQiOiJQTU1vYmlsZUNvbGxlY3Rpb25CYWNrR3JvdW5kSW1hZ2UiLCJjYXRhbG9nSWQiOiJwbGFjZW1ha2Vyc0NvbnRlbnRDYXRhbG9nIiwiY2F0YWxvZ1ZlcnNpb24iOiJPbmxpbmUifQ==",
                typeCode: "SimpleResponsiveBannerComponent",
                parents: "cmsitem_00005000",
              },
              promoType: "OTHER",
              source: "MOBILE",
              tagText: "PROMOTION",
              children: "PMMobileCollectionBackGroundImage PMMobileTagImage",
              ctaAction: "www.placemakers.co.nz/online/landscaping/decking#inspiration",
              mainTitle: "Decking Inspiration",
              synchronizationBlocked: "false",
              tagImage: {
                container: "false",
                uid: "PMMobileTagImage",
                name: "PM Mobile Tag Image",
                synchronizationBlocked: "false",
                uuid: "eyJpdGVtSWQiOiJQTU1vYmlsZVRhZ0ltYWdlIiwiY2F0YWxvZ0lkIjoicGxhY2VtYWtlcnNDb250ZW50Q2F0YWxvZyIsImNhdGFsb2dWZXJzaW9uIjoiT25saW5lIn0=",
                typeCode: "CMSImageComponent",
                parents: "cmsitem_00005000 cmsitem_00004002",
              },
            },
            {
              uid: "cmsitem_00004002",
              uuid: "eyJpdGVtSWQiOiJjbXNpdGVtXzAwMDA0MDAyIiwiY2F0YWxvZ0lkIjoicGxhY2VtYWtlcnNDb250ZW50Q2F0YWxvZyIsImNhdGFsb2dWZXJzaW9uIjoiT25saW5lIn0=",
              typeCode: "PMMarketingTileComponent",
              modifiedtime: "2022-12-14T20:03:21.876+13:00",
              name: "New Feature Tile - Image 3",
              container: "false",
              darkBackground: "true",
              ctaText: "Learn More",
              footerText:
                "Spend less time creating and tracking your quotes. Check out our NEW Quotes Feature available under JOBS or CLICK HERE to find out more",
              backgroundImage: {
                container: "false",
                uid: "PMMobileProductBackGroundImage",
                name: "winmorejobs",
                synchronizationBlocked: "false",
                media: {
                  widescreen: {
                    code: "livetrack-banner.jpg",
                    mime: "image/jpeg",
                    altText: "livetrack-banner.jpg",
                    url: "/medias/sys_master/root/hf3/ha2/9087433572382/livetrack-banner/livetrack-banner.jpg",
                  },
                },
                uuid: "eyJpdGVtSWQiOiJQTU1vYmlsZVByb2R1Y3RCYWNrR3JvdW5kSW1hZ2UiLCJjYXRhbG9nSWQiOiJwbGFjZW1ha2Vyc0NvbnRlbnRDYXRhbG9nIiwiY2F0YWxvZ1ZlcnNpb24iOiJPbmxpbmUifQ==",
                typeCode: "SimpleResponsiveBannerComponent",
                parents: "cmsitem_00004002",
              },
              promoType: "OTHER",
              source: "MOBILE",
              tagText: "DeWalt Promotion",
              children: "PMMobileProductBackGroundImage PMMobileTagImage",
              ctaAction: "www.placemakers.co.nz/online/quotes-estimates",
              mainTitle: "Want to win more jobs?",
              synchronizationBlocked: "false",
              tagImage: {
                container: "false",
                uid: "PMMobileTagImage",
                name: "PM Mobile Tag Image",
                synchronizationBlocked: "false",
                uuid: "eyJpdGVtSWQiOiJQTU1vYmlsZVRhZ0ltYWdlIiwiY2F0YWxvZ0lkIjoicGxhY2VtYWtlcnNDb250ZW50Q2F0YWxvZyIsImNhdGFsb2dWZXJzaW9uIjoiT25saW5lIn0=",
                typeCode: "CMSImageComponent",
                parents: "cmsitem_00005000 cmsitem_00004002",
              },
            },
          ],
        },
      },
      {
        slotId: "PMAppHeaderSlot",
        slotUuid: "eyJpdGVtSWQiOiJQTUFwcEhlYWRlclNsb3QiLCJjYXRhbG9nSWQiOiJwbGFjZW1ha2Vyc0NvbnRlbnRDYXRhbG9nIiwiY2F0YWxvZ1ZlcnNpb24iOiJPbmxpbmUifQ==",
        position: "PMAppHeader",
        name: "Header",
        slotShared: false,
        components: {
          component: [],
        },
      },
      {
        slotId: "PMCategoryTilesSlot1",
        slotUuid: "eyJpdGVtSWQiOiJQTUNhdGVnb3J5VGlsZXNTbG90MSIsImNhdGFsb2dJZCI6InBsYWNlbWFrZXJzQ29udGVudENhdGFsb2ciLCJjYXRhbG9nVmVyc2lvbiI6Ik9ubGluZSJ9",
        position: "PMCategoryTiles1",
        name: "PMCategory Tiles Slot1",
        slotShared: false,
        components: {
          component: [
            {
              uid: "PMCategoryTile1",
              uuid: "eyJpdGVtSWQiOiJQTUNhdGVnb3J5VGlsZTEiLCJjYXRhbG9nSWQiOiJwbGFjZW1ha2Vyc0NvbnRlbnRDYXRhbG9nIiwiY2F0YWxvZ1ZlcnNpb24iOiJPbmxpbmUifQ==",
              typeCode: "PMCategoryComponent",
              modifiedtime: "2022-12-14T23:11:31.534+13:00",
              name: "PM Category Tile 1",
              container: "false",
              synchronizationBlocked: "false",
              media: {
                widescreen: {
                  code: "Building_Products.jpg",
                  mime: "image/jpeg",
                  url: "/medias/sys_master/images/h6a/h84/9087566675998/Building_Products/Building-Products.jpg",
                },
              },
              categoryName: "Mobiles & Electronics",
              categoryId: "410",
              urlLink: "BB1",
              categoryDescription: "Building Products",
            },
            {
              uid: "PMCategoryTile2",
              uuid: "eyJpdGVtSWQiOiJQTUNhdGVnb3J5VGlsZTIiLCJjYXRhbG9nSWQiOiJwbGFjZW1ha2Vyc0NvbnRlbnRDYXRhbG9nIiwiY2F0YWxvZ1ZlcnNpb24iOiJPbmxpbmUifQ==",
              typeCode: "PMCategoryComponent",
              modifiedtime: "2022-12-14T23:11:31.535+13:00",
              name: "PM Category Tile 2",
              container: "false",
              synchronizationBlocked: "false",
              media: {
                widescreen: {
                  code: "Doors_Joinery_Hardware.jpg",
                  mime: "image/jpeg",
                  url: "/medias/sys_master/images/h2a/h88/9087566544926/Doors_Joinery_Hardware/Doors-Joinery-Hardware.jpg",
                },
              },
              categoryName: "Accessories",
              categoryId: "260",
              urlLink: "BB2",
              categoryDescription: "Doors, Windows & Joinery Hardware",
            },
            {
              uid: "PMCategoryTile3",
              uuid: "eyJpdGVtSWQiOiJQTUNhdGVnb3J5VGlsZTMiLCJjYXRhbG9nSWQiOiJwbGFjZW1ha2Vyc0NvbnRlbnRDYXRhbG9nIiwiY2F0YWxvZ1ZlcnNpb24iOiJPbmxpbmUifQ==",
              typeCode: "PMCategoryComponent",
              modifiedtime: "2022-12-14T23:11:31.535+13:00",
              name: "PM Category Tile 3",
              container: "false",
              synchronizationBlocked: "false",
              media: {
                widescreen: {
                  code: "Adhesives_Sealants.jpg",
                  mime: "image/jpeg",
                  url: "/medias/sys_master/images/h3a/h8b/9087566479390/Adhesives_Sealants/Adhesives-Sealants.jpg",
                },
              },
              categoryName: "Daily Offers",
              categoryId: "do1",
              urlLink: "CC2",
              categoryDescription: "Adhesives & Sealants",
            },
            {
              uid: "PMCategoryTile4",
              uuid: "eyJpdGVtSWQiOiJQTUNhdGVnb3J5VGlsZTQiLCJjYXRhbG9nSWQiOiJwbGFjZW1ha2Vyc0NvbnRlbnRDYXRhbG9nIiwiY2F0YWxvZ1ZlcnNpb24iOiJPbmxpbmUifQ==",
              typeCode: "PMCategoryComponent",
              modifiedtime: "2022-12-14T23:11:31.535+13:00",
              name: "PM Category Tile 4",
              container: "false",
              synchronizationBlocked: "false",
              media: {
                widescreen: {
                  code: "Sheds_Buildings.jpg",
                  mime: "image/jpeg",
                  url: "/medias/sys_master/images/h80/h88/9087566512158/Sheds_Buildings/Sheds-Buildings.jpg",
                },
              },
              categoryName: "Shoes",
              categoryId: "do1",
              urlLink: "BB3",
              categoryDescription: "Sheds & Buildings",
            },
            {
              uid: "PMCategoryTile5",
              uuid: "eyJpdGVtSWQiOiJQTUNhdGVnb3J5VGlsZTUiLCJjYXRhbG9nSWQiOiJwbGFjZW1ha2Vyc0NvbnRlbnRDYXRhbG9nIiwiY2F0YWxvZ1ZlcnNpb24iOiJPbmxpbmUifQ==",
              typeCode: "PMCategoryComponent",
              modifiedtime: "2022-12-14T23:11:31.536+13:00",
              name: "PM Category Tile 5",
              container: "false",
              synchronizationBlocked: "false",
              media: {
                widescreen: {
                  code: "Fastenings_Hardware.jpg",
                  mime: "image/jpeg",
                  url: "/medias/sys_master/images/hc3/h81/9087566708766/Fastenings_Hardware/Fastenings-Hardware.jpg",
                },
              },
              categoryName: "Clearance",
              categoryId: "810",
              urlLink: "CC1",
              categoryDescription: "Fastenings & General Hardware",
            },
            {
              uid: "PMCategoryTile6",
              uuid: "eyJpdGVtSWQiOiJQTUNhdGVnb3J5VGlsZTYiLCJjYXRhbG9nSWQiOiJwbGFjZW1ha2Vyc0NvbnRlbnRDYXRhbG9nIiwiY2F0YWxvZ1ZlcnNpb24iOiJPbmxpbmUifQ==",
              typeCode: "PMCategoryComponent",
              modifiedtime: "2022-12-14T23:11:31.537+13:00",
              name: "PM Category Tile 6",
              container: "false",
              synchronizationBlocked: "false",
              media: {
                widescreen: {
                  code: "Timber_Plywood.jpg",
                  mime: "image/jpeg",
                  url: "/medias/sys_master/images/hd2/h87/9087566577694/Timber_Plywood/Timber-Plywood.jpg",
                },
              },
              categoryName: "Daily Offers",
              categoryId: "810",
              urlLink: "AA1",
              categoryDescription: "Timber & Plywood",
            },
          ],
        },
      },
      {
        slotId: "PMCategoryTilesSlot2",
        slotUuid: "eyJpdGVtSWQiOiJQTUNhdGVnb3J5VGlsZXNTbG90MiIsImNhdGFsb2dJZCI6InBsYWNlbWFrZXJzQ29udGVudENhdGFsb2ciLCJjYXRhbG9nVmVyc2lvbiI6Ik9ubGluZSJ9",
        position: "PMCategoryTiles2",
        name: "PMCategory Tiles Slot2",
        slotShared: false,
        components: {
          component: [
            {
              uid: "PMCategoryTile9",
              uuid: "eyJpdGVtSWQiOiJQTUNhdGVnb3J5VGlsZTkiLCJjYXRhbG9nSWQiOiJwbGFjZW1ha2Vyc0NvbnRlbnRDYXRhbG9nIiwiY2F0YWxvZ1ZlcnNpb24iOiJPbmxpbmUifQ==",
              typeCode: "PMCategoryComponent",
              modifiedtime: "2022-12-14T23:11:31.541+13:00",
              name: "PM Category Tile 9",
              container: "false",
              synchronizationBlocked: "false",
              media: {
                widescreen: {
                  code: "Safety_Ladders.jpg",
                  mime: "image/jpeg",
                  url: "/medias/sys_master/images/hc1/h84/9087566643230/Safety_Ladders/Safety-Ladders.jpg",
                },
              },
              categoryName: "Safety & Ladders",
              categoryId: "810",
              urlLink: "CC4",
              categoryDescription: "Safety & Ladders",
            },
            {
              uid: "PMCategoryTile10",
              uuid: "eyJpdGVtSWQiOiJQTUNhdGVnb3J5VGlsZTEwIiwiY2F0YWxvZ0lkIjoicGxhY2VtYWtlcnNDb250ZW50Q2F0YWxvZyIsImNhdGFsb2dWZXJzaW9uIjoiT25saW5lIn0=",
              typeCode: "PMCategoryComponent",
              modifiedtime: "2022-12-14T23:11:31.541+13:00",
              name: "PM Category Tile 10",
              container: "false",
              synchronizationBlocked: "false",
              media: {
                widescreen: {
                  code: "Tools.jpg",
                  mime: "image/jpeg",
                  url: "/medias/sys_master/images/h02/h81/9087566774302/Tools/Tools.jpg",
                },
              },
              categoryName: "Tools",
              categoryId: "810",
              urlLink: "CC3",
              categoryDescription: "Tools",
            },
            {
              uid: "PMCategoryTile11",
              uuid: "eyJpdGVtSWQiOiJQTUNhdGVnb3J5VGlsZTExIiwiY2F0YWxvZ0lkIjoicGxhY2VtYWtlcnNDb250ZW50Q2F0YWxvZyIsImNhdGFsb2dWZXJzaW9uIjoiT25saW5lIn0=",
              typeCode: "PMCategoryComponent",
              modifiedtime: "2022-12-14T23:11:31.584+13:00",
              name: "PM Category Tile 11",
              container: "false",
              synchronizationBlocked: "false",
              media: {
                widescreen: {
                  code: "Cleaning_Site_Consumables.jpg",
                  mime: "image/jpeg",
                  url: "/medias/sys_master/images/h59/h81/9087566741534/Cleaning_Site_Consumables/Cleaning-Site-Consumables.jpg",
                },
              },
              categoryName: "Cleaning & Site Consumables",
              categoryId: "810",
              urlLink: "CC5",
              categoryDescription: "Cleaning & Site Consumables",
            },
            {
              uid: "PMCategoryTile12",
              uuid: "eyJpdGVtSWQiOiJQTUNhdGVnb3J5VGlsZTEyIiwiY2F0YWxvZ0lkIjoicGxhY2VtYWtlcnNDb250ZW50Q2F0YWxvZyIsImNhdGFsb2dWZXJzaW9uIjoiT25saW5lIn0=",
              typeCode: "PMCategoryComponent",
              modifiedtime: "2022-12-14T23:11:31.583+13:00",
              name: "PM Category Tile 12",
              container: "false",
              synchronizationBlocked: "false",
              media: {
                widescreen: {
                  code: "Electrical_Heating_Cooling.jpg",
                  mime: "image/jpeg",
                  url: "/medias/sys_master/images/h32/h7a/9087566970910/Electrical_Heating_Cooling/Electrical-Heating-Cooling.jpg",
                },
              },
              categoryName: "Electrical & Heating-Cooling",
              categoryId: "810",
              urlLink: "DD1",
              categoryDescription: "Electrical & Heating-Cooling",
            },
            {
              uid: "PMCategoryTile13",
              uuid: "eyJpdGVtSWQiOiJQTUNhdGVnb3J5VGlsZTEzIiwiY2F0YWxvZ0lkIjoicGxhY2VtYWtlcnNDb250ZW50Q2F0YWxvZyIsImNhdGFsb2dWZXJzaW9uIjoiT25saW5lIn0=",
              typeCode: "PMCategoryComponent",
              modifiedtime: "2022-12-14T23:11:31.587+13:00",
              name: "PM Category Tile 13",
              container: "false",
              synchronizationBlocked: "false",
              media: {
                widescreen: {
                  code: "Wardrobe_Storage_Flooring.jpg",
                  mime: "image/jpeg",
                  url: "/medias/sys_master/images/h04/h7e/9087566839838/Wardrobe_Storage_Flooring/Wardrobe-Storage-Flooring.jpg",
                },
              },
              categoryName: "Wardrobes, Storage & Flooring",
              categoryId: "810",
              urlLink: "DD5",
              categoryDescription: "Wardrobes, Storage & Flooring",
            },
            {
              uid: "PMCategoryTile14",
              uuid: "eyJpdGVtSWQiOiJQTUNhdGVnb3J5VGlsZTE0IiwiY2F0YWxvZ0lkIjoicGxhY2VtYWtlcnNDb250ZW50Q2F0YWxvZyIsImNhdGFsb2dWZXJzaW9uIjoiT25saW5lIn0=",
              typeCode: "PMCategoryComponent",
              modifiedtime: "2022-12-14T23:11:31.588+13:00",
              name: "PM Category Tile 14",
              container: "false",
              synchronizationBlocked: "false",
              media: {
                widescreen: {
                  code: "Bathroom_Plumbing.jpg",
                  mime: "image/jpeg",
                  url: "/medias/sys_master/images/h9c/h7a/9087566938142/Bathroom_Plumbing/Bathroom-Plumbing.jpg",
                },
              },
              categoryName: "Bathrooms & Plumbing",
              categoryId: "810",
              urlLink: "DD2",
              categoryDescription: "Bathrooms & Plumbing",
            },
            {
              uid: "PMCategoryTile15",
              uuid: "eyJpdGVtSWQiOiJQTUNhdGVnb3J5VGlsZTE1IiwiY2F0YWxvZ0lkIjoicGxhY2VtYWtlcnNDb250ZW50Q2F0YWxvZyIsImNhdGFsb2dWZXJzaW9uIjoiT25saW5lIn0=",
              typeCode: "PMCategoryComponent",
              modifiedtime: "2022-12-14T23:11:31.585+13:00",
              name: "PM Category Tile 15",
              container: "false",
              synchronizationBlocked: "false",
              media: {
                widescreen: {
                  code: "Painting_Decorating.jpg",
                  mime: "image/jpeg",
                  url: "/medias/sys_master/images/h9a/h7d/9087566872606/Painting_Decorating/Painting-Decorating.jpg",
                },
              },
              categoryName: "Paint & Decorating",
              categoryId: "810",
              urlLink: "DD3",
              categoryDescription: "Paint & Decorating",
            },
            {
              uid: "PMCategoryTile16",
              uuid: "eyJpdGVtSWQiOiJQTUNhdGVnb3J5VGlsZTE2IiwiY2F0YWxvZ0lkIjoicGxhY2VtYWtlcnNDb250ZW50Q2F0YWxvZyIsImNhdGFsb2dWZXJzaW9uIjoiT25saW5lIn0=",
              typeCode: "PMCategoryComponent",
              modifiedtime: "2022-12-14T23:11:31.586+13:00",
              name: "PM Category Tile 16",
              container: "false",
              synchronizationBlocked: "false",
              media: {
                widescreen: {
                  code: "Kitchens_Laundries.jpg",
                  mime: "image/jpeg",
                  url: "/medias/sys_master/images/h5b/h7e/9087566807070/Kitchens_Laundries/Kitchens-Laundries.jpg",
                },
              },
              categoryName: "Kitchens & Laundries",
              categoryId: "810",
              urlLink: "DD4",
              categoryDescription: "Kitchens & Laundries",
            },
          ],
        },
      },
    ],
  },
  label: "mobileLandingPage",
};

export const carouselData = [
  {
    title: "Up to 55% off Sunglasses and Eyewear",
    body: "Ray Ban, Chanel, Prada, Vogue, Emporio Armani Tiffany and more..",
    imgUrl: "https://picsum.photos/id/11/200/300",
  },
  {
    title: "Up to 55% off Sunglasses and Eyewear",
    body: "Ray Ban, Chanel, Prada, Vogue, Emporio Armani Tiffany and more..",
    imgUrl: "https://picsum.photos/id/10/200/300",
  },
  {
    title: "Up to 55% off Sunglasses and Eyewear",
    body: "Ray Ban, Chanel, Prada, Vogue, Emporio Armani Tiffany and more..",
    imgUrl: "https://picsum.photos/id/12/200/300",
  },
];
