const images = {
  closeButton: require("../Images/closeButton/CloseButton.svg"),
  openEye: require("../Images/openEye/OpenEye.svg"),
  closeEye: require("../Images/closeEye/CloseEye.svg"),
  bestsellerBatch: require("../Images/bestSellerBatch/bestsellerBatch.svg"),
  bestsellerBatch_ar: require("../Images/bestSellerBatch/bestsellerBatchreverse.svg"),
  BackIcon: require("../Images/BackIcon/BackIcon.png"),
  BackIcon_ar: require("../Images/BackIcon/BackIcon_ar.png"),
  DeleteIcon: require("../Images/DeleteIcon/DeleteIcon.png"),
  DeleteCartItemIcon: require("../Images/DeleteIcon/deleteCartItem.png"),
  Logo: require("../Images/Logo/Logo.png"),
  contactUs: require("../Images/externalLink/externalLink.png"),
  Logo_ar: require("../Images/LogoAr/LogoAr.png"),
  CartHeader: require("../Images/CartHeader/CartHeader2x.png"),
  CartHeader_ar: require("../Images/CartHeader/CartHeader-modified2x.png"),
  Wish: require("../Images/Wishlist/Wishlist_2x.png"),
  SearchBold: require("../Images/SearchBold/SearchBold.png"),
  SearchBold_ar: require("../Images/SearchBold/SearchBold_ar.png"),
  NextIcon: require("../Images/nextIcon/nextIcon.png"),
  NextIcon_ar: require("../Images/nextIcon/nextIcon_ar.png"),
  CarosalBackIcon: require("../Images/carosalBackIcon/carosalBackIcon.png"),
  CarosalBackIcon_ar: require("../Images/carosalBackIcon/carosalBackIcon_ar.png"),
  StockGreen: require("../Images/stock/sockGreen.png"),
  StockRed: require("../Images/stock/stockRed.png"),
  CartEmpty: require("../Images/cartEmpty/cartEmptyThumbNail.png"),
  WebCloseIcon: require("../Images/webViewIcons/webCloseIcon.png"),
  WebCloseIcon_ar: require("../Images/webViewIcons/webCloseIcon.png"),
  WebReloadIcon: require("../Images/webViewIcons/webReloadIcon.png"),
  WebReloadIcon_ar: require("../Images/webViewIcons/webReloadIcon.png"),
  WebBackIcon: require("../Images/webViewIcons/webBackIconwhite.png"),
  WebBackIcon_ar: require("../Images/webViewIcons/webNextIconwhite.png"),
  WebNextIcon: require("../Images/webViewIcons/webNextIconwhite.png"),
  WebNextIcon_ar: require("../Images/webViewIcons/webBackIconwhite.png"),
  Success: require("../Images/SuccessCheck/SuccessCheck.png"),
};

export default images;
