export const cartInputEntries = [
  {
    availableForPickup: true,
    basePrice: {
      currencyIso: "NZD",
      formattedValue: "$54.36",
      priceType: "BUY",
      value: 54.36,
    },
    configurationInfos: [],
    customProductFlag: false,
    decimalQty: 1,
    deliveryOrder: true,
    entryNumber: 0,
    estimateProductStock: 0,
    product: {
      alternateProductCount: 0,
      appUomFormat: "11",
      availableForPickup: true,
      baseOptions: [],
      categories: [
        {
          code: "BC11PE",
          name: "Aqualine",
          url: "/building-products/plasterboard/performance-board/aqualine/c/BC11PE",
        },
      ],
      code: "2801876",
      configurable: false,
      description:
        "The GIB Aqualine Wallboard measuring 2400 mm x 1200 mm x 13 mm is designed to use in bathrooms, en-suites, laundries, toilets and showers. Wallboard acts as a barrier to moisture and prevents any serious damage to the underlying framing. Water-resistant core consists of special polymers that offers a superior base for paint, tile and wallpaper finishes.",
      display: "SPECIAL",
      expressOrder: false,
      hasAlternateProducts: false,
      hasNoQuantity: 0,
      hasRelatedProducts: false,
      images: [
        {
          altText: "GIB|Aqualine Wallboard|2400 x 1200 x 13 mm Green Face Paper Gypsum|12531",
          format: "zoom",
          imageType: "PRIMARY",
          url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/1012153_GIB_12556.jpg",
        },
        {
          altText: "GIB|Aqualine Wallboard|2400 x 1200 x 13 mm Green Face Paper Gypsum|12531",
          format: "product",
          imageType: "PRIMARY",
          url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/1012153_GIB_12556.jpg",
        },
        {
          altText: "GIB|Aqualine Wallboard|2400 x 1200 x 13 mm Green Face Paper Gypsum|12531",
          format: "thumbnail",
          imageType: "PRIMARY",
          url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/1012153_GIB_12556.jpg",
        },
        {
          altText: "GIB|Aqualine Wallboard|2400 x 1200 x 13 mm Green Face Paper Gypsum|12531",
          format: "cartIcon",
          imageType: "PRIMARY",
          url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/1012153_GIB_12556.jpg",
        },
      ],
      manufacturer: "GIB",
      manufacturerId: "12531",
      name: "GIB|Aqualine Wallboard|2400 x 1200 x 13 mm Green Face Paper Gypsum|12531",
      pmExclusive: false,
      price: {
        currencyIso: "NZD",
        formattedValue: "$54.36",
        priceType: "BUY",
        value: 54.36,
      },
      purchasable: true,
      relatedProductCount: 0,
      retailPrice: {
        currencyIso: "NZD",
        formattedValue: "$70.43",
        priceType: "BUY",
        value: 70.43,
      },
      retailPriceGstInclusive: {
        currencyIso: "NZD",
        formattedValue: "$80.99",
        priceType: "BUY",
        value: 80.99,
      },
      sellOrderMultiple: 0,
      specialProdWithAlphaSkuFlag: true,
      specialProduct: true,
      stock: {
        isValueRounded: false,
        pmStockQuantity: "1",
        statusCode: "2",
        stockLevelStatus: "lowStock",
      },
      timberProductFlag: false,
      unitCode: "EA",
      uomFormat: "11",
      url: "/building-products/plasterboard/performance-board/aqualine/gibaqualine-wallboard2400-x-1200-x-13-mm-green-face-paper-gypsum12531/p/2801876",
    },
    quantity: 1,
    retailPrice: {
      currencyIso: "NZD",
      formattedValue: "$0.00",
      priceType: "BUY",
      value: 0,
    },
    selectedConfiguration: [],
    totalPrice: {
      currencyIso: "NZD",
      formattedValue: "$54.36",
      priceType: "BUY",
      value: 54.36,
    },
    unit: "EA",
    updateable: true,
  },
  {
    availableForPickup: true,
    basePrice: {
      currencyIso: "NZD",
      formattedValue: "$0.00",
      priceType: "BUY",
      value: 0,
    },
    configurationInfos: [],
    customProductFlag: false,
    decimalQty: 1,
    deliveryOrder: true,
    entryNumber: 1,
    estimateProductStock: 0,
    product: {
      alternateProductCount: 0,
      appUomFormat: "7.2",
      availableForPickup: true,
      baseOptions: [],
      categories: [],
      code: "1354828",
      configurable: false,
      description: "Non structural rough sawn merch grade timber suitable for exposed above ground applications. An economical option for general purpose use.",
      display: "PURCHASABLE",
      expressOrder: false,
      hasAlternateProducts: false,
      hasNoQuantity: 0,
      hasRelatedProducts: false,
      manufacturerId: "2030225",
      name: "Radiata Rough Sawn Merch Grade Timber H3.2 CCA Treated 150 x 40mm",
      pmExclusive: false,
      price: {
        currencyIso: "NZD",
        formattedValue: "$0.00",
        priceType: "BUY",
        value: 0,
      },
      purchasable: true,
      relatedProductCount: 0,
      retailPrice: {
        currencyIso: "NZD",
        formattedValue: "$0.00",
        priceType: "BUY",
        value: 0,
      },
      retailPriceGstInclusive: {
        currencyIso: "NZD",
        formattedValue: "$0.00",
        priceType: "BUY",
        value: 0,
      },
      sellOrderMultiple: 0,
      specialProdWithAlphaSkuFlag: false,
      specialProduct: false,
      stock: {
        isValueRounded: false,
        pmStockQuantity: "0",
        statusCode: "3",
        stockLevelStatus: "outOfStock",
      },
      timberProductFlag: true,
      unitCode: "LM",
      uomFormat: "7.2",
      url: "/c/radiata-rough-sawn-merch-grade-timber-h32-cca-treated-150-x-40mm/p/1354828",
    },
    quantity: 1,
    retailPrice: {
      currencyIso: "NZD",
      formattedValue: "$0.00",
      priceType: "BUY",
      value: 0,
    },
    selectedConfiguration: [],
    totalPrice: {
      currencyIso: "NZD",
      formattedValue: "$0.00",
      priceType: "BUY",
      value: 0,
    },
    unit: "LM",
    updateable: true,
  },
];

export const cartOutputEntries = [
  {
    availableForPickup: true,
    basePrice: {
      currencyIso: "NZD",
      formattedValue: "$54.36",
      priceType: "BUY",
      value: 54.36,
    },
    configurationInfos: [],
    customProductFlag: false,
    decimalQty: 1,
    deliveryOrder: true,
    entryNumber: 0,
    estimateProductStock: 0,
    product: {
      alternateProductCount: 0,
      appUomFormat: "11",
      availableForPickup: true,
      baseOptions: [],
      categories: [
        {
          code: "BC11PE",
          name: "Aqualine",
          url: "/building-products/plasterboard/performance-board/aqualine/c/BC11PE",
        },
      ],
      code: "2801876",
      configurable: false,
      description:
        "The GIB Aqualine Wallboard measuring 2400 mm x 1200 mm x 13 mm is designed to use in bathrooms, en-suites, laundries, toilets and showers. Wallboard acts as a barrier to moisture and prevents any serious damage to the underlying framing. Water-resistant core consists of special polymers that offers a superior base for paint, tile and wallpaper finishes.",
      display: "SPECIAL",
      expressOrder: false,
      hasAlternateProducts: false,
      hasNoQuantity: 0,
      hasRelatedProducts: false,
      images: [
        {
          altText: "GIB|Aqualine Wallboard|2400 x 1200 x 13 mm Green Face Paper Gypsum|12531",
          format: "zoom",
          imageType: "PRIMARY",
          url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/1012153_GIB_12556.jpg",
        },
        {
          altText: "GIB|Aqualine Wallboard|2400 x 1200 x 13 mm Green Face Paper Gypsum|12531",
          format: "product",
          imageType: "PRIMARY",
          url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/1012153_GIB_12556.jpg",
        },
        {
          altText: "GIB|Aqualine Wallboard|2400 x 1200 x 13 mm Green Face Paper Gypsum|12531",
          format: "thumbnail",
          imageType: "PRIMARY",
          url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/1012153_GIB_12556.jpg",
        },
        {
          altText: "GIB|Aqualine Wallboard|2400 x 1200 x 13 mm Green Face Paper Gypsum|12531",
          format: "cartIcon",
          imageType: "PRIMARY",
          url: "https://pimstorageauesit.blob.core.windows.net/placemakers/media-assets/1012153_GIB_12556.jpg",
        },
      ],
      manufacturer: "GIB",
      manufacturerId: "12531",
      name: "GIB|Aqualine Wallboard|2400 x 1200 x 13 mm Green Face Paper Gypsum|12531",
      pmExclusive: false,
      price: {
        currencyIso: "NZD",
        formattedValue: "$54.36",
        priceType: "BUY",
        value: 54.36,
      },
      purchasable: true,
      relatedProductCount: 0,
      retailPrice: {
        currencyIso: "NZD",
        formattedValue: "$70.43",
        priceType: "BUY",
        value: 70.43,
      },
      retailPriceGstInclusive: {
        currencyIso: "NZD",
        formattedValue: "$80.99",
        priceType: "BUY",
        value: 80.99,
      },
      sellOrderMultiple: 0,
      specialProdWithAlphaSkuFlag: true,
      specialProduct: true,
      stock: {
        isValueRounded: false,
        pmStockQuantity: "1",
        statusCode: "2",
        stockLevelStatus: "lowStock",
      },
      timberProductFlag: false,
      unitCode: "EA",
      uomFormat: "11",
      url: "/building-products/plasterboard/performance-board/aqualine/gibaqualine-wallboard2400-x-1200-x-13-mm-green-face-paper-gypsum12531/p/2801876",
    },
    quantity: 1,
    retailPrice: {
      currencyIso: "NZD",
      formattedValue: "$0.00",
      priceType: "BUY",
      value: 0,
    },
    selectedConfiguration: [],
    totalPrice: {
      currencyIso: "NZD",
      formattedValue: "$54.36",
      priceType: "BUY",
      value: 54.36,
    },
    unit: "EA",
    updateable: true,
  },
  {
    availableForPickup: true,
    basePrice: {
      currencyIso: "NZD",
      formattedValue: "$0.00",
      priceType: "BUY",
      value: 0,
    },
    configurationInfos: [],
    customProductFlag: false,
    decimalQty: 1,
    deliveryOrder: true,
    entryNumber: 1,
    estimateProductStock: 0,
    product: {
      alternateProductCount: 0,
      appUomFormat: "7.2",
      availableForPickup: true,
      baseOptions: [],
      categories: [],
      code: "1354828",
      configurable: false,
      description: "Non structural rough sawn merch grade timber suitable for exposed above ground applications. An economical option for general purpose use.",
      display: "PURCHASABLE",
      expressOrder: false,
      hasAlternateProducts: false,
      hasNoQuantity: 0,
      hasRelatedProducts: false,
      manufacturerId: "2030225",
      name: "Radiata Rough Sawn Merch Grade Timber H3.2 CCA Treated 150 x 40mm",
      pmExclusive: false,
      price: {
        currencyIso: "NZD",
        formattedValue: "$0.00",
        priceType: "BUY",
        value: 0,
      },
      purchasable: true,
      relatedProductCount: 0,
      retailPrice: {
        currencyIso: "NZD",
        formattedValue: "$0.00",
        priceType: "BUY",
        value: 0,
      },
      retailPriceGstInclusive: {
        currencyIso: "NZD",
        formattedValue: "$0.00",
        priceType: "BUY",
        value: 0,
      },
      sellOrderMultiple: 0,
      specialProdWithAlphaSkuFlag: false,
      specialProduct: false,
      stock: {
        isValueRounded: false,
        pmStockQuantity: "0",
        statusCode: "3",
        stockLevelStatus: "outOfStock",
      },
      timberProductFlag: true,
      unitCode: "LM",
      uomFormat: "7.2",
      url: "/c/radiata-rough-sawn-merch-grade-timber-h32-cca-treated-150-x-40mm/p/1354828",
    },
    quantity: 1,
    retailPrice: {
      currencyIso: "NZD",
      formattedValue: "$0.00",
      priceType: "BUY",
      value: 0,
    },
    selectedConfiguration: [],
    totalPrice: {
      currencyIso: "NZD",
      formattedValue: "$0.00",
      priceType: "BUY",
      value: 0,
    },
    unit: "LM",
    updateable: true,
  },
];

export const isPOAProductInput = {
  availableForPickup: true,
  basePrice: {
    currencyIso: "NZD",
    formattedValue: "$0.00",
    priceType: "BUY",
    value: 0,
  },
  configurationInfos: [],
  customProductFlag: false,
  decimalQty: 1,
  deliveryOrder: true,
  entryNumber: 1,
  estimateProductStock: 0,
  product: {
    alternateProductCount: 0,
    appUomFormat: "7.2",
    availableForPickup: true,
    baseOptions: [],
    categories: [],
    code: "1354828",
    configurable: false,
    description: "Non structural rough sawn merch grade timber suitable for exposed above ground applications. An economical option for general purpose use.",
    display: "PURCHASABLE",
    expressOrder: false,
    hasAlternateProducts: false,
    hasNoQuantity: 0,
    hasRelatedProducts: false,
    manufacturerId: "2030225",
    name: "Radiata Rough Sawn Merch Grade Timber H3.2 CCA Treated 150 x 40mm",
    pmExclusive: false,
    price: {
      currencyIso: "NZD",
      formattedValue: "$0.00",
      priceType: "BUY",
      value: 0,
    },
    purchasable: true,
    relatedProductCount: 0,
    retailPrice: {
      currencyIso: "NZD",
      formattedValue: "$0.00",
      priceType: "BUY",
      value: 0,
    },
    retailPriceGstInclusive: {
      currencyIso: "NZD",
      formattedValue: "$0.00",
      priceType: "BUY",
      value: 0,
    },
    sellOrderMultiple: 0,
    specialProdWithAlphaSkuFlag: false,
    specialProduct: false,
    stock: {
      isValueRounded: false,
      pmStockQuantity: "0",
      statusCode: "3",
      stockLevelStatus: "outOfStock",
    },
    timberProductFlag: true,
    unitCode: "LM",
    uomFormat: "7.2",
    url: "/c/radiata-rough-sawn-merch-grade-timber-h32-cca-treated-150-x-40mm/p/1354828",
  },
  quantity: 1,
  retailPrice: {
    currencyIso: "NZD",
    formattedValue: "$0.00",
    priceType: "BUY",
    value: 0,
  },
  selectedConfiguration: [],
  totalPrice: {
    currencyIso: "NZD",
    formattedValue: "$0.00",
    priceType: "BUY",
    value: 0,
  },
  unit: "LM",
  updateable: true,
};
