require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

def __apply_Xcode_14_3_RC_post_install_workaround(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        current_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
        minimum_target = 11.0
        if current_target.to_f < minimum_target.to_f
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = minimum_target
        end
      end
    end
  end

abstract_target 'SACCCommonPods' do
config = use_native_modules!
# Flags change depending on the env values.
flags = get_default_flags()

# pod 'FBSDKCoreKit'
# pod 'FBSDKLoginKit'
pod 'Firebase', :modular_headers => true
pod 'FirebaseCore', :modular_headers => true
pod 'GoogleUtilities', :modular_headers => true
# pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'
# pod 'RNFirebase', :path => '../node_modules/@react-native-firebase/app/ios'

# $RNFirebaseAsStaticFramework = true
#  use_frameworks! :linkage => :static
#  $RNFirebaseAsStaticFramework = true
use_react_native!(
:path => config[:reactNativePath],
# Hermes is now enabled by default. Disable by setting this flag to false.
# Upcoming versions of React Native may rely on get_default_flags(), but
# we make it explicit here to aid in the React Native upgrade process.
:hermes_enabled => false,
:fabric_enabled => flags[:fabric_enabled],
# Enables Flipper.
#
# Note that if you have use_frameworks! enabled, Flipper will not work and
# you should disable the next line.
:flipper_configuration => FlipperConfiguration.enabled,
# An absolute path to your application root.
:app_path => "#{Pod::Config.instance.installation_root}/.."
)
target 'SACCTests' do
inherit! :complete
# Pods for testing
end
target 'SACC SIT' do
# Pods for testing
end
target 'SACC UAT' do
# Pods for testing
end
target 'SACC' do
end

# Permissions
permissions_path = '../node_modules/react-native-permissions/ios'
pod 'react-native-config/Extension', :path => '../node_modules/react-native-config'
post_install do |installer|
react_native_post_install(
installer,
# Set `mac_catalyst_enabled` to `true` in order to apply patches
# necessary for Mac Catalyst builds
:mac_catalyst_enabled => true
)
__apply_Xcode_12_5_M1_post_install_workaround(installer)
__apply_Xcode_14_3_RC_post_install_workaround(installer)
end
end
